services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - SQL_SERVER_USER=sa
      - SQL_SERVER_PASSWORD=Abc@123123#1010
      - SQL_SERVER_SERVER=db
      - SQL_SERVER_DATABASE=clothes369
      - NODE_ENV=development
      - PORT=3000
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - /app/node_modules
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Abc@123123#1010
      - MSSQL_PID=Express
    ports:
      - "1435:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
volumes:
  sqlserver_data:
