INSERT INTO categories (parentCategoryID, name) VALUES
(NULL, 'Men'),
(NULL, 'Women'),
(NULL, 'Kids'),
(NULL, 'Accessories'),
(NULL, 'Footwear'),
(2, 'Subcategory 6'),
(2, 'Subcategory 7'),
(1, 'Subcategory 8'),
(2, 'Subcategory 9'),
(1, 'Subcategory 10'),
(5, 'Subcategory 11'),
(4, 'Subcategory 12'),
(4, 'Subcategory 13'),
(4, 'Subcategory 14'),
(5, 'Subcategory 15'),
(3, 'Subcategory 16'),
(5, 'Subcategory 17'),
(2, 'Subcategory 18'),
(5, 'Subcategory 19'),
(1, 'Subcategory 20');
